---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/admin_user/{admin_user_id}/books":
    post:
      summary: Creates a book
      tags:
      - Books
      parameters:
      - name: admin_user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: book created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: integer
              required:
              - name
              - price
          application/xml:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: integer
              required:
              - name
              - price
  "/api/v1/admin_user/{admin_user_id}/books/{id}":
    get:
      summary: Retrieves a Book
      tags:
      - Books
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: admin_user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  price:
                    type: integer
                required:
                - id
                - name
                - price
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  price:
                    type: integer
                required:
                - id
                - name
                - price
        '404':
          description: book not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
